# Generated by Django 5.1.7 on 2025-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='asin',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='imgURL',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isEditorsPick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isGoodReadsChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isKindleUnlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='productURL',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='soldBy',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stars',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=False),
        ),
    ]
