# Generated by Django 5.1.7 on 2025-03-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_isbn_book_asin_rename_authors_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_code',
        ),
    ]
