# Generated by Django 5.1.7 on 2025-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('soldBy', models.CharField(blank=True, max_length=255, null=True)),
                ('productURL', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('imgURL', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('isKindleUnlimited', models.BooleanField(default=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('isBestSeller', models.BooleanField(default=False)),
                ('isEditorsPick', models.BooleanField(default=False)),
                ('isGoodReadsChoice', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
